spring:
  cloud:
    function:
      definition: processor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        processor-in-0:
          destination: order-events
          group: customer-payment-group
        processor-out-0:
          destination: payment-events
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.example.common.events.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///paymentdb
    username: sa
    password:

  #datasource:
   # url: jdbc:h2:mem:paymentdb